# Generated by Django 5.1.4 on 2024-12-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
