# Generated by Django 5.1.4 on 2024-12-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_alter_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='user',
        ),
    ]
