# Generated by Django 5.1.4 on 2024-12-25 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_booking_delete_fee'),
        ('studentapp', '0008_rename_username_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.room'),
        ),
    ]
