# Generated by Django 5.1.4 on 2024-12-27 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_alter_student_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='reg_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
