# Generated by Django 5.1.4 on 2024-12-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0010_fee_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
