# Generated by Django 5.1.4 on 2025-01-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0014_rename_payment_id_fee_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='razorpay_payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
