# Generated by Django 5.1.4 on 2025-01-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0016_alter_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='razorpay_payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
