# Generated by Django 5.1.4 on 2025-01-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0018_fee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='description',
            field=models.TextField(),
        ),
    ]
