# Generated by Django 5.1.4 on 2024-12-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.student'),
        ),
    ]
