# Generated by Django 5.1.4 on 2024-12-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupied',
            field=models.IntegerField(default=0),
        ),
    ]
