# Generated by Django 5.1.4 on 2024-12-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_room_occupied'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, unique=True)),
                ('adm_no', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
