# Generated by Django 5.1.4 on 2024-12-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_rename_user_userprofile_username'),
        ('studentapp', '0005_alter_student_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
