# Generated by Django 5.1.4 on 2024-12-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_booking_delete_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
