# Generated by Django 5.1.4 on 2025-01-01 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='time_posted',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
