# Generated by Django 5.1.4 on 2025-01-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_notice_time_posted_alter_notice_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='time_posted',
        ),
        migrations.AlterField(
            model_name='notice',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
