# Generated by Django 5.1.4 on 2025-01-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_alter_room_occupied_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
